services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://cjohnson:Zurich.15@192.168.1.100:27017/weatherApp # Adresse MongoDB sur la machine hôte
    networks:
      - app-network # Réseau partagé avec le frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3001 # Variable d'environnement pour pointer vers le backend
    networks:
      - app-network # Réseau partagé avec le backend

networks:
  app-network:
    driver: bridge
