name: Deploy Weather App

on:
  push:
    branches:
      - main # Déclenche le workflow à chaque push sur la branche "main"

jobs:
  deploy:
    runs-on: self-hosted # Spécifie que le workflow s'exécute sur ton self-hosted runner

    steps:
      # 1. Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Construire et déployer avec Docker Compose
      - name: Deploy application
        run: |
          docker-compose pull
          docker-compose up -d --build

      # 3. Créer un fichier texte avec les logs du déploiement
      - name: Create deployment log
        run: |
          echo "Deployment Logs - $(date)" > /home/cjohnson/Documents/logs/deployment-logs.txt
          echo "Backend and Frontend deployed successfully." >> /home/cjohnson/Documents/logs/deployment-logs.txt
          echo "Deployed on $(hostname)" >> /home/cjohnson/Documents/logs/deployment-logs.txt